/** Central registry of TanStack Query keys, so invalidations stay consistent. */
export const queryKeys = {
  me: ["me"] as const,
  dashboard: (workspaceId: string) => ["dashboard", workspaceId] as const,
  tasksToday: ["tasks", "today"] as const,
  projects: (filters?: Record<string, string | undefined>) => ["projects", filters ?? {}] as const,
  project: (id: string) => ["projects", id] as const,
  projectOverview: (id: string) => ["projects", id, "overview"] as const,
  projectActivity: (id: string) => ["projects", id, "activity"] as const,
  projectTemplates: ["project-templates"] as const,
  tasks: (filters?: Record<string, string | undefined>) => ["tasks", filters ?? {}] as const,
  task: (id: string) => ["tasks", id] as const,
  milestones: (projectId: string) => ["milestones", projectId] as const,
  notes: (projectId: string, taskId?: string) => ["notes", projectId, taskId ?? null] as const,
  timeEntries: (filters?: Record<string, string | undefined>) => ["time-entries", filters ?? {}] as const,
  timeEntriesActive: ["time-entries", "active"] as const,
  timeReports: (params?: Record<string, string | undefined>) => ["time-entries", "reports", params ?? {}] as const,
  budget: (projectId: string) => ["budget", projectId] as const,
  budgetAlerts: (projectId: string) => ["budget", projectId, "alerts"] as const,
  costVendors: () => ["cost-vendors"] as const,
  costSubscriptions: (params?: Record<string, string | undefined>) => ["cost-subscriptions", params ?? {}] as const,
  costExpenses: (params?: Record<string, string | undefined>) => ["cost-expenses", params ?? {}] as const,
  costPendingReview: () => ["cost-expenses", "pending-review"] as const,
  costSummary: (month: string) => ["cost-summary", month] as const,
  financialOverview: (params?: Record<string, string | undefined>) => ["financial-overview", params ?? {}] as const,
  automations: (filters?: Record<string, string | undefined>) => ["automations", filters ?? {}] as const,
  automationRuns: (filters?: Record<string, string | undefined>) => ["automation-runs", filters ?? {}] as const,
  automationRun: (id: string) => ["automation-runs", id] as const,
  webhookStatus: ["automations", "webhook-status"] as const,
  weeklyReview: (weekStart?: string) => ["weekly-review", weekStart ?? null] as const,
  workspace: (id: string) => ["workspace", id] as const,
  workspaceActivity: (id: string, filters?: Record<string, string | undefined>) =>
    ["workspace", id, "activity", filters ?? {}] as const,
};
